# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dectroo/Desktop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dectroo/Desktop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dectroo/Desktop/CMakeFiles /home/dectroo/Desktop/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dectroo/Desktop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DiffBotClient

# Build rule for target.
DiffBotClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DiffBotClient
.PHONY : DiffBotClient

# fast build rule for target.
DiffBotClient/fast:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/build
.PHONY : DiffBotClient/fast

src/DiffBotClient.o: src/DiffBotClient.cpp.o
.PHONY : src/DiffBotClient.o

# target to build an object file
src/DiffBotClient.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/DiffBotClient.cpp.o
.PHONY : src/DiffBotClient.cpp.o

src/DiffBotClient.i: src/DiffBotClient.cpp.i
.PHONY : src/DiffBotClient.i

# target to preprocess a source file
src/DiffBotClient.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/DiffBotClient.cpp.i
.PHONY : src/DiffBotClient.cpp.i

src/DiffBotClient.s: src/DiffBotClient.cpp.s
.PHONY : src/DiffBotClient.s

# target to generate assembly for a file
src/DiffBotClient.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/DiffBotClient.cpp.s
.PHONY : src/DiffBotClient.cpp.s

src/JSONArray.o: src/JSONArray.cpp.o
.PHONY : src/JSONArray.o

# target to build an object file
src/JSONArray.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONArray.cpp.o
.PHONY : src/JSONArray.cpp.o

src/JSONArray.i: src/JSONArray.cpp.i
.PHONY : src/JSONArray.i

# target to preprocess a source file
src/JSONArray.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONArray.cpp.i
.PHONY : src/JSONArray.cpp.i

src/JSONArray.s: src/JSONArray.cpp.s
.PHONY : src/JSONArray.s

# target to generate assembly for a file
src/JSONArray.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONArray.cpp.s
.PHONY : src/JSONArray.cpp.s

src/JSONBoolean.o: src/JSONBoolean.cpp.o
.PHONY : src/JSONBoolean.o

# target to build an object file
src/JSONBoolean.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONBoolean.cpp.o
.PHONY : src/JSONBoolean.cpp.o

src/JSONBoolean.i: src/JSONBoolean.cpp.i
.PHONY : src/JSONBoolean.i

# target to preprocess a source file
src/JSONBoolean.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONBoolean.cpp.i
.PHONY : src/JSONBoolean.cpp.i

src/JSONBoolean.s: src/JSONBoolean.cpp.s
.PHONY : src/JSONBoolean.s

# target to generate assembly for a file
src/JSONBoolean.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONBoolean.cpp.s
.PHONY : src/JSONBoolean.cpp.s

src/JSONNull.o: src/JSONNull.cpp.o
.PHONY : src/JSONNull.o

# target to build an object file
src/JSONNull.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONNull.cpp.o
.PHONY : src/JSONNull.cpp.o

src/JSONNull.i: src/JSONNull.cpp.i
.PHONY : src/JSONNull.i

# target to preprocess a source file
src/JSONNull.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONNull.cpp.i
.PHONY : src/JSONNull.cpp.i

src/JSONNull.s: src/JSONNull.cpp.s
.PHONY : src/JSONNull.s

# target to generate assembly for a file
src/JSONNull.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONNull.cpp.s
.PHONY : src/JSONNull.cpp.s

src/JSONNumber.o: src/JSONNumber.cpp.o
.PHONY : src/JSONNumber.o

# target to build an object file
src/JSONNumber.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONNumber.cpp.o
.PHONY : src/JSONNumber.cpp.o

src/JSONNumber.i: src/JSONNumber.cpp.i
.PHONY : src/JSONNumber.i

# target to preprocess a source file
src/JSONNumber.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONNumber.cpp.i
.PHONY : src/JSONNumber.cpp.i

src/JSONNumber.s: src/JSONNumber.cpp.s
.PHONY : src/JSONNumber.s

# target to generate assembly for a file
src/JSONNumber.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONNumber.cpp.s
.PHONY : src/JSONNumber.cpp.s

src/JSONObject.o: src/JSONObject.cpp.o
.PHONY : src/JSONObject.o

# target to build an object file
src/JSONObject.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONObject.cpp.o
.PHONY : src/JSONObject.cpp.o

src/JSONObject.i: src/JSONObject.cpp.i
.PHONY : src/JSONObject.i

# target to preprocess a source file
src/JSONObject.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONObject.cpp.i
.PHONY : src/JSONObject.cpp.i

src/JSONObject.s: src/JSONObject.cpp.s
.PHONY : src/JSONObject.s

# target to generate assembly for a file
src/JSONObject.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONObject.cpp.s
.PHONY : src/JSONObject.cpp.s

src/JSONSerializer.o: src/JSONSerializer.cpp.o
.PHONY : src/JSONSerializer.o

# target to build an object file
src/JSONSerializer.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONSerializer.cpp.o
.PHONY : src/JSONSerializer.cpp.o

src/JSONSerializer.i: src/JSONSerializer.cpp.i
.PHONY : src/JSONSerializer.i

# target to preprocess a source file
src/JSONSerializer.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONSerializer.cpp.i
.PHONY : src/JSONSerializer.cpp.i

src/JSONSerializer.s: src/JSONSerializer.cpp.s
.PHONY : src/JSONSerializer.s

# target to generate assembly for a file
src/JSONSerializer.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONSerializer.cpp.s
.PHONY : src/JSONSerializer.cpp.s

src/JSONString.o: src/JSONString.cpp.o
.PHONY : src/JSONString.o

# target to build an object file
src/JSONString.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONString.cpp.o
.PHONY : src/JSONString.cpp.o

src/JSONString.i: src/JSONString.cpp.i
.PHONY : src/JSONString.i

# target to preprocess a source file
src/JSONString.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONString.cpp.i
.PHONY : src/JSONString.cpp.i

src/JSONString.s: src/JSONString.cpp.s
.PHONY : src/JSONString.s

# target to generate assembly for a file
src/JSONString.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONString.cpp.s
.PHONY : src/JSONString.cpp.s

src/JSONValue.o: src/JSONValue.cpp.o
.PHONY : src/JSONValue.o

# target to build an object file
src/JSONValue.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONValue.cpp.o
.PHONY : src/JSONValue.cpp.o

src/JSONValue.i: src/JSONValue.cpp.i
.PHONY : src/JSONValue.i

# target to preprocess a source file
src/JSONValue.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONValue.cpp.i
.PHONY : src/JSONValue.cpp.i

src/JSONValue.s: src/JSONValue.cpp.s
.PHONY : src/JSONValue.s

# target to generate assembly for a file
src/JSONValue.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/JSONValue.cpp.s
.PHONY : src/JSONValue.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tinycurl.o: src/tinycurl.cpp.o
.PHONY : src/tinycurl.o

# target to build an object file
src/tinycurl.cpp.o:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/tinycurl.cpp.o
.PHONY : src/tinycurl.cpp.o

src/tinycurl.i: src/tinycurl.cpp.i
.PHONY : src/tinycurl.i

# target to preprocess a source file
src/tinycurl.cpp.i:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/tinycurl.cpp.i
.PHONY : src/tinycurl.cpp.i

src/tinycurl.s: src/tinycurl.cpp.s
.PHONY : src/tinycurl.s

# target to generate assembly for a file
src/tinycurl.cpp.s:
	$(MAKE) -f CMakeFiles/DiffBotClient.dir/build.make CMakeFiles/DiffBotClient.dir/src/tinycurl.cpp.s
.PHONY : src/tinycurl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DiffBotClient"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/DiffBotClient.o"
	@echo "... src/DiffBotClient.i"
	@echo "... src/DiffBotClient.s"
	@echo "... src/JSONArray.o"
	@echo "... src/JSONArray.i"
	@echo "... src/JSONArray.s"
	@echo "... src/JSONBoolean.o"
	@echo "... src/JSONBoolean.i"
	@echo "... src/JSONBoolean.s"
	@echo "... src/JSONNull.o"
	@echo "... src/JSONNull.i"
	@echo "... src/JSONNull.s"
	@echo "... src/JSONNumber.o"
	@echo "... src/JSONNumber.i"
	@echo "... src/JSONNumber.s"
	@echo "... src/JSONObject.o"
	@echo "... src/JSONObject.i"
	@echo "... src/JSONObject.s"
	@echo "... src/JSONSerializer.o"
	@echo "... src/JSONSerializer.i"
	@echo "... src/JSONSerializer.s"
	@echo "... src/JSONString.o"
	@echo "... src/JSONString.i"
	@echo "... src/JSONString.s"
	@echo "... src/JSONValue.o"
	@echo "... src/JSONValue.i"
	@echo "... src/JSONValue.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tinycurl.o"
	@echo "... src/tinycurl.i"
	@echo "... src/tinycurl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

